/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Roadmap = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'steps' : IDL.Vec(IDL.Text),
});
export const Sector = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'description' : IDL.Text,
});
export const AssessmentStatus = IDL.Variant({
  'notStarted' : IDL.Null,
  'completed' : IDL.Null,
  'inProgress' : IDL.Null,
});
export const SkillAssessment = IDL.Record({
  'id' : IDL.Text,
  'status' : AssessmentStatus,
  'name' : IDL.Text,
});
export const JobRole = IDL.Record({
  'role' : IDL.Text,
  'jobId' : IDL.Text,
  'description' : IDL.Text,
  'typicalEducation' : IDL.Text,
  'requirements' : IDL.Vec(IDL.Text),
});
export const UserProfile = IDL.Record({
  'completedAssessments' : IDL.Vec(SkillAssessment),
  'name' : IDL.Text,
  'role' : UserRole,
  'email' : IDL.Text,
  'savedJobs' : IDL.Vec(JobRole),
  'profilePicture' : IDL.Opt(IDL.Text),
});
export const Question = IDL.Record({
  'id' : IDL.Nat,
  'answers' : IDL.Vec(IDL.Text),
  'text' : IDL.Text,
});
export const UserQuizResult = IDL.Record({
  'userId' : IDL.Text,
  'answers' : IDL.Vec(IDL.Nat),
  'sector' : Sector,
  'timestamp' : IDL.Int,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'authenticateUser' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
  'changePassword' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Bool], []),
  'getAvailableRoadmaps' : IDL.Func([IDL.Nat], [IDL.Vec(Roadmap)], ['query']),
  'getAvailableSectors' : IDL.Func([], [IDL.Vec(Sector)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getRandomQuestions' : IDL.Func([IDL.Nat], [IDL.Vec(Question)], ['query']),
  'getRecommendedJobRoles' : IDL.Func([IDL.Nat], [IDL.Vec(JobRole)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'register' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'submitQuizAnswers' : IDL.Func(
      [Sector, IDL.Vec(IDL.Nat)],
      [UserQuizResult],
      [],
    ),
  'updateUserProfile' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Opt(IDL.Text)],
      [UserProfile],
      [],
    ),
  'usernameExists' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Roadmap = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'steps' : IDL.Vec(IDL.Text),
  });
  const Sector = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'description' : IDL.Text,
  });
  const AssessmentStatus = IDL.Variant({
    'notStarted' : IDL.Null,
    'completed' : IDL.Null,
    'inProgress' : IDL.Null,
  });
  const SkillAssessment = IDL.Record({
    'id' : IDL.Text,
    'status' : AssessmentStatus,
    'name' : IDL.Text,
  });
  const JobRole = IDL.Record({
    'role' : IDL.Text,
    'jobId' : IDL.Text,
    'description' : IDL.Text,
    'typicalEducation' : IDL.Text,
    'requirements' : IDL.Vec(IDL.Text),
  });
  const UserProfile = IDL.Record({
    'completedAssessments' : IDL.Vec(SkillAssessment),
    'name' : IDL.Text,
    'role' : UserRole,
    'email' : IDL.Text,
    'savedJobs' : IDL.Vec(JobRole),
    'profilePicture' : IDL.Opt(IDL.Text),
  });
  const Question = IDL.Record({
    'id' : IDL.Nat,
    'answers' : IDL.Vec(IDL.Text),
    'text' : IDL.Text,
  });
  const UserQuizResult = IDL.Record({
    'userId' : IDL.Text,
    'answers' : IDL.Vec(IDL.Nat),
    'sector' : Sector,
    'timestamp' : IDL.Int,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'authenticateUser' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
    'changePassword' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Bool], []),
    'getAvailableRoadmaps' : IDL.Func([IDL.Nat], [IDL.Vec(Roadmap)], ['query']),
    'getAvailableSectors' : IDL.Func([], [IDL.Vec(Sector)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getRandomQuestions' : IDL.Func([IDL.Nat], [IDL.Vec(Question)], ['query']),
    'getRecommendedJobRoles' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(JobRole)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'register' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'submitQuizAnswers' : IDL.Func(
        [Sector, IDL.Vec(IDL.Nat)],
        [UserQuizResult],
        [],
      ),
    'updateUserProfile' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Opt(IDL.Text)],
        [UserProfile],
        [],
      ),
    'usernameExists' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };