/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type AssessmentStatus = { 'notStarted' : null } |
  { 'completed' : null } |
  { 'inProgress' : null };
export interface JobRole {
  'role' : string,
  'jobId' : string,
  'description' : string,
  'typicalEducation' : string,
  'requirements' : Array<string>,
}
export interface Question {
  'id' : bigint,
  'answers' : Array<string>,
  'text' : string,
}
export interface Roadmap {
  'id' : bigint,
  'name' : string,
  'steps' : Array<string>,
}
export interface Sector {
  'id' : bigint,
  'name' : string,
  'description' : string,
}
export interface SkillAssessment {
  'id' : string,
  'status' : AssessmentStatus,
  'name' : string,
}
export interface UserProfile {
  'completedAssessments' : Array<SkillAssessment>,
  'name' : string,
  'role' : UserRole,
  'email' : string,
  'savedJobs' : Array<JobRole>,
  'profilePicture' : [] | [string],
}
export interface UserQuizResult {
  'userId' : string,
  'answers' : Array<bigint>,
  'sector' : Sector,
  'timestamp' : bigint,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'authenticateUser' : ActorMethod<[string, string], boolean>,
  'changePassword' : ActorMethod<[string, string, string], boolean>,
  'getAvailableRoadmaps' : ActorMethod<[bigint], Array<Roadmap>>,
  'getAvailableSectors' : ActorMethod<[], Array<Sector>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getRandomQuestions' : ActorMethod<[bigint], Array<Question>>,
  'getRecommendedJobRoles' : ActorMethod<[bigint], Array<JobRole>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'register' : ActorMethod<[string, string], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'submitQuizAnswers' : ActorMethod<[Sector, Array<bigint>], UserQuizResult>,
  'updateUserProfile' : ActorMethod<
    [string, string, [] | [string]],
    UserProfile
  >,
  'usernameExists' : ActorMethod<[string], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];